"""Domain handlers for Google APIs."""

from .apps_script import (
    cancel_operation_handler,
    execute_operation_handler,
    get_script_content_handler,
    prepare_script_update_handler,
    restore_script_backup_handler,
    create_script_project_handler,
)
from .calendar import (
    calendar_create_meeting_handler,
    calendar_find_free_slots_handler,
    create_event_handler,
    list_events_handler,
)
from .docs import (
    append_to_doc_handler,
    create_doc_handler,
    doc_export_pdf_handler,
    doc_fill_template_handler,
    read_doc_handler,
)
from .drive import (
    create_folder_handler,
    drive_copy_file_handler,
    drive_list_permissions_handler,
    drive_revoke_public_handler,
    drive_search_advanced_handler,
    find_files_handler,
    move_file_handler,
    share_file_handler,
)
from .gmail import (
    batch_delete_emails_handler,
    create_draft_handler,
    delete_email_handler,
    get_gmail_profile_handler,
    gmail_archive_handler,
    gmail_label_apply_handler,
    gmail_search_and_summarize_handler,
    list_emails_handler,
    read_email_handler,
    send_draft_handler,
    send_email_handler,
)
from .sheets import (
    add_sheet_handler,
    append_row_handler,
    clear_range_handler,
    create_spreadsheet_handler,
    get_spreadsheet_meta_handler,
    read_sheet_handler,
    sheet_create_filter_view_handler,
    sheet_create_named_range_handler,
    sheet_export_csv_handler,
    sheet_find_replace_handler,
    update_sheet_handler,
)

__all__ = [
    "find_files_handler",
    "read_sheet_handler",
    "append_row_handler",
    "update_sheet_handler",
    "create_script_project_handler",
    "get_script_content_handler",
    "prepare_script_update_handler",
    "execute_operation_handler",
    "cancel_operation_handler",
    "restore_script_backup_handler",
    "read_doc_handler",
    "create_doc_handler",
    "append_to_doc_handler",
    "doc_fill_template_handler",
    "doc_export_pdf_handler",
    "create_spreadsheet_handler",
    "add_sheet_handler",
    "clear_range_handler",
    "sheet_create_filter_view_handler",
    "sheet_export_csv_handler",
    "sheet_find_replace_handler",
    "sheet_create_named_range_handler",
    "get_spreadsheet_meta_handler",
    "send_email_handler",
    "send_draft_handler",
    "get_gmail_profile_handler",
    "create_draft_handler",
    "list_emails_handler",
    "read_email_handler",
    "delete_email_handler",
    "batch_delete_emails_handler",
    "gmail_search_and_summarize_handler",
    "gmail_archive_handler",
    "gmail_label_apply_handler",
    "list_events_handler",
    "create_event_handler",
    "calendar_find_free_slots_handler",
    "calendar_create_meeting_handler",
    "create_folder_handler",
    "move_file_handler",
    "share_file_handler",
    "drive_search_advanced_handler",
    "drive_list_permissions_handler",
    "drive_revoke_public_handler",
    "drive_copy_file_handler",
]
